spring:
  port: 5000
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/income_estimator?createDatabaseIfNotExist=true
    username: root
    password: password
    initialization-mode: always
    jpa:
      show-sql: true
      generate-ddl: true
      hibernate:
        ddl-auto: create
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          show_sql: true
          format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace